# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(884, 651)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.test_id_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_id_line_edit.sizePolicy().hasHeightForWidth())
        self.test_id_line_edit.setSizePolicy(sizePolicy)
        self.test_id_line_edit.setMinimumSize(QtCore.QSize(340, 0))
        self.test_id_line_edit.setReadOnly(True)
        self.test_id_line_edit.setObjectName("test_id_line_edit")
        self.horizontalLayout_2.addWidget(self.test_id_line_edit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.status_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_line_edit.sizePolicy().hasHeightForWidth())
        self.status_line_edit.setSizePolicy(sizePolicy)
        self.status_line_edit.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(45)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.status_line_edit.setFont(font)
        self.status_line_edit.setText("")
        self.status_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.status_line_edit.setPlaceholderText("")
        self.status_line_edit.setObjectName("status_line_edit")
        self.gridLayout.addWidget(self.status_line_edit, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.current_pfc_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_pfc_line_edit.sizePolicy().hasHeightForWidth())
        self.current_pfc_line_edit.setSizePolicy(sizePolicy)
        self.current_pfc_line_edit.setReadOnly(True)
        self.current_pfc_line_edit.setObjectName("current_pfc_line_edit")
        self.horizontalLayout.addWidget(self.current_pfc_line_edit)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.start_push_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_push_button.sizePolicy().hasHeightForWidth())
        self.start_push_button.setSizePolicy(sizePolicy)
        self.start_push_button.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setPointSize(56)
        font.setBold(True)
        font.setWeight(75)
        self.start_push_button.setFont(font)
        self.start_push_button.setObjectName("start_push_button")
        self.gridLayout.addWidget(self.start_push_button, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 884, 25))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_enter_calibration_mode = QtWidgets.QAction(MainWindow)
        self.action_enter_calibration_mode.setObjectName("action_enter_calibration_mode")
        self.action_change_pass_fail_force_criteria = QtWidgets.QAction(MainWindow)
        self.action_change_pass_fail_force_criteria.setObjectName("action_change_pass_fail_force_criteria")
        self.action_change_Password = QtWidgets.QAction(MainWindow)
        self.action_change_Password.setObjectName("action_change_Password")
        self.action_change_output_path = QtWidgets.QAction(MainWindow)
        self.action_change_output_path.setObjectName("action_change_output_path")
        self.menuSettings.addAction(self.action_change_pass_fail_force_criteria)
        self.menuSettings.addAction(self.action_enter_calibration_mode)
        self.menuSettings.addAction(self.action_change_output_path)
        self.menuSettings.addAction(self.action_change_Password)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Steelcase NDDTS"))
        self.label_2.setText(_translate("MainWindow", "Test ID:"))
        self.label.setText(_translate("MainWindow", "Current Pass/Fail Criteria [lbf]:"))
        self.start_push_button.setText(_translate("MainWindow", "Start New Test"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.action_enter_calibration_mode.setText(_translate("MainWindow", "Enter Calibration Mode..."))
        self.action_change_pass_fail_force_criteria.setText(_translate("MainWindow", "Change Pass/Fail Force Criteria..."))
        self.action_change_Password.setText(_translate("MainWindow", "Change Password..."))
        self.action_change_output_path.setText(_translate("MainWindow", "Change Output Path..."))

